version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wb_reviews_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: wb_reviews
    ports:
      - "5433:5432"  # Внешний порт 5433, внутренний 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d wb_reviews"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: